# nixpacks.toml
[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "nodejs", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase'"]

[start]
cmd = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app"